#!/usr/bin/env python

import os
import yaml

if __name__ == "__main__":
    app_store_path="//mnt/froody/shared/repos/rocon/app_store"
    app_store_yaml_path=os.path.join(app_store_path,"applications.yaml")
    if ( os.path.exists(app_store_yaml_path) ):
        os.remove(os.path.join(app_store_path,"applications.yaml"))
    packages = os.listdir(app_store_path)
    app_store_yaml = open(app_store_yaml_path, 'w')
    app_store_yaml.write("apps:\n")
    for package in packages:
        package_files = os.listdir(os.path.join(app_store_path,package))
        package_yaml_path = ""
        package_name = ""
	for package_file in package_files:
            (root,ext) = os.path.splitext(package_file)
            if ( ext == ".yaml" ):
                package_name = root
		package_yaml_path = os.path.join(app_store_path,package,package_file)
        package_yaml = open(package_yaml_path, 'r')
        package_data = yaml.load(package_yaml)
        package_display_name = package_data['display']
        app_store_yaml.write(" - app: %s/%s\n"%(package,package_name))
        app_store_yaml.write("   display: %s\n"%package_display_name)
        app_store_yaml.write("   debian: %s\n"%package)
    app_store_yaml.close()

