#!/bin/bash

DIR=/opt/servers/apache/www/rocon/apps/dists

cd ${DIR}/lucid/i386
dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
cd ${DIR}/maverick/i386
dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
cd ${DIR}/oneiric/i386
dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz

